In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/drive/MyDrive/23-1 KUBIG 추천시스템 프로젝트/데이터/Train_user_idx.csv')
df

,ID,User-ID,Book-ID,Book-Rating,Age,Location,Book-Title,Book-Author,Year-Of-Publication,Publisher,town,state,country
0,TRAIN_000012,USER_00003,BOOK_006281,9,24.0,"magdeburg, sachsen-anhalt, germany",Wir sind Erinnerung. GedÃ?Â¤chtnis und PersÃ?Â...,Daniel L. Schacter,2001.0,Rowohlt Tb.,magdeburg,sachsen-anhalt,germany
1,TRAIN_000013,USER_00003,BOOK_017583,7,24.0,"magdeburg, sachsen-anhalt, germany",2061. Odyssee III. Roman.,Arthur C. Clarke,2000.0,Heyne,magdeburg,sachsen-anhalt,germany
2,TRAIN_000014,USER_00003,BOOK_047847,7,24.0,"magdeburg, sachsen-anhalt, germany",Die Jury. Roman.,John Grisham,1992.0,Heyne,magdeburg,sachsen-anhalt,germany
3,TRAIN_000015,USER_00003,BOOK_058657,8,24.0,"magdeburg, sachsen-anhalt, germany",Frisch gepreÃ?Â?t.,Susanne FrÃ?Â¶hlich,2000.0,Ullstein Buchverlage GmbH &amp; Co. KG / Ullst...,magdeburg,sachsen-anhalt,germany
4,TRAIN_000016,USER_00003,BOOK_097106,6,24.0,"magdeburg, sachsen-anhalt, germany",Hitlers Helfer.,Guido Knopp,1998.0,Goldmann,magdeburg,sachsen-anhalt,germany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
697104,TRAIN_871381,USER_92093,BOOK_267033,10,37.0,"lakewood, colorado, usa","Tea Time/Tradition, Presentation, and Recipes ...",M. Dalton King,1992.0,Running Press Book Publishers,lakewood,colorado,usa
697105,TRAIN_871382,USER_92093,BOOK_267657,8,37.0,"lakewood, colorado, usa","Gates of Zion (Thoene, Bodie, Zion Chronicles,...",Bodie Thoene,1986.0,Bethany House,lakewood,colorado,usa
697106,TRAIN_871383,USER_92093,BOOK_267890,0,37.0,"lakewood, colorado, usa","Girlfriends: Invisible Bonds, Enduring Ties",Carmen Renee Berry,1995.0,Wildcat Canyon Press,lakewood,colorado,usa
697107,TRAIN_871384,USER_92093,BOOK_268377,8,37.0,"lakewood, colorado, usa","When Hope Springs New (Canadian West, Book 4)",Janette Oke,1986.0,Bethany House,lakewood,colorado,usa
697108,TRAIN_871385,USER_92093,BOOK_269242,7,37.0,"lakewood, colorado, usa",A Sand County Almanac and Sketches Here and Th...,Aldo Leopold,1989.0,Oxford University Press,lakewood,colorado,usa

# state 처리

In [ ]:
from collections import Counter

def show_most_frequent(column):
    counter = Counter(column)
    most_common = counter.most_common()

    for value, count in most_common:
        print(f'{value}: {count}')

show_most_frequent(df['state'])

# califonia, texas, ontario, missouri, florida

california: 74617
texas: 30246
ontario: 27956
missouri: 24918
florida: 23000
washington: 21365
illinois: 21057
georgia: 20286
virginia: 20046
minnesota: 18999
new york: 18346
pennsylvania: 16124
north carolina: 15590
n/a: 15086
ohio: 13627
england: 13276
new jersey: 13067
: 12837
oregon: 12523
michigan: 12410
maryland: 12215
arizona: 9954
british columbia: 9801
wisconsin: 9432
colorado: 9394
alberta: 8981
nebraska: 8565
tennessee: 8471
massachusetts: 8306
kentucky: 7516
hawaii: 6177
west virginia: 6166
south carolina: 5848
connecticut: 5800
saskatchewan: 5342
indiana: 5304
alabama: 5197
iowa: 4696
maine: 4682
new mexico: 4619
alaska: 4451
nevada: 4367
oklahoma: 4255
new hampshire: 3678
new south wales: 3479
arkansas: 3373
nordrhein-westfalen: 3370
kansas: 3228
victoria: 3197
utah: 3080
louisiana: 2779
nova scotia: 2689
hessen: 2485
new brunswick: 2438
quebec: 2304
lisboa: 2267
canterbury: 2173
catalunya: 1864
mississippi: 1768
selangor: 1559
south australia: 1554
manitoba: 1484
bayern: 1302
baden-wuerttemberg: 1287
madrid: 1277
barcelona: 1266
idaho: 1263
western australia: 1253
baden-württemberg: 1232
tehran: 1231
surrey: 1229
rhode island: 1214
ile de france: 1207
álava: 1131
ga.: 1094
wales: 1022
hamburg: 1001
south dakota: 999
vermont: 967
montana: 871
gelderland: 818
queensland: 817
scotland: 795
distrito nacional: 795
rheinland-pfalz: 781
wien: 776
berlin: 773
melaka: 757
otago: 755
delaware: 752
ile-de-france: 752
ap: 625
setúbal: 615
porto: 559
north dakota: 535
alsace: 530
basel-stadt: 503
niedersachsen: 486
bretagne: 482
sarawak: 468
dc: 454
uusimaa: 451
newfoundland: 424
pas de calais: 423
wyoming: 421
overijssel: 406
paris: 388
kent: 386
sachsen: 377
suffolk: 371
vizcaya: 363
toscana: 362
australian capital territory: 354
nord: 345
rhône-alpes: 342
hampshire: 341
são paulo: 328
iasi: 325
zuid-holland: 321
vienna: 319
stockholm: 313
derbyshire: 291
noord holland: 284
noord-holland: 283
steiermark: 281
loures: 277
vaud: 276
shanghai: 276
prahova: 268
ourense: 261
oslo: 250
lisbon: 237
pontevedra: 236
haute-garonne: 235
bern: 232
utrecht: 227
zürich: 216
manawatu: 216
sevilla: 215
bremen: 211
federal territory: 211
illes balears: 201
doha: 201
ae: 198
valencia: 190
vlaams-brabant: 182
norfolk: 176
lombardia: 176
yukon territory: 174
pirkanmaa: 168
zaragoza: 168
fribourg: 167
cambridgeshire: 165
wilayah persekutuan: 162
penang: 160
london: 159
seine saint-denis: 159
bavaria: 155
pays de la loire: 154
aragon: 147
co. dublin: 146
schleswig-holstein: 145
planet: 145
lazio: 142
languedoc roussillon: 140
ticino: 139
auckland: 139
hauts-de-seine: 134
taranaki: 131
cantabria: 129
tokyo: 129
midi-pyrénées: 127
rhône alpes: 126
lancashire: 126
cheshire: 124
northern territory: 124
kuala lumpur: 122
oberoesterreich: 121
galati: 121
central: 114
ca: 114
sachsen-anhalt: 113
noord-brabant: 112
savoie: 112
québec: 110
wiltshire: 110
north yorkshire: 110
tirol: 109
loire atlantique: 108
dublin: 108
aragón: 106
san josé: 106
geneva: 102
canary islands: 100
luzern: 100
merseyside: 98
nan: 96
marlborough: 96
northern ireland: 95
franche-comté: 95
normandie: 94
emilia romagna: 93
south yorkshire: 92
wellington: 90
barreiro: 90
taiwan: 89
west yorkshire: 86
champagne-ardenne: 86
w.p: 85
national capital region: 84
bihor: 84
isle of man: 82
tyne & wear: 82
selangor darul ehsan: 80
manila: 79
rangoon: 77
berkshire: 76
ga: 76
woj. mazowieckie: 76
makati: 75
prince edward island: 74
cadiz: 72
limburg: 70
leinster: 70
nj: 70
etelä-suomen lääni: 69
nottinghamshire: 68
okinawa: 67
channel islands: 66
d.n.: 65
bizkaia: 65
baleares: 65
tx: 64
zuerich: 64
kildare: 62
athens: 62
s yorkshire: 61
picardie: 60
puerto rico: 60
gautang: 59
buckinghamshire: 58
zug: 58
la rioja: 58
kuwait: 57
coimbra: 57
nrw: 57
rhone-alpes: 56
nm: 56
rio grande do sul: 55
moving: 55
bedfordshire: 55
takaka: 54
patrick henry village: 54
albay: 53
cáceres: 53
west sussex: 51
saitama: 51
pernambuco: 51
andalucía: 51
lothian: 50
piemonte: 49
catalonia: 49
limpopo: 47
alicante: 46
andalucia: 46
greater manchester: 45
gipuzkoa: 45
wa: 45
asturias: 44
armed forces europe: 44
singapore: 43
rhone: 43
metro manila: 43
braga: 43
sabah: 42
trentino alto adige: 42
buenos aires: 42
córdoba: 42
minas gerais: 42
prague: 41
pohjois-pohjanmaa: 41
ok: 40
namur: 40
ribatejo: 39
seixal: 39
bc: 39
euskadi: 39
worcestershire: 38
espinho: 38
zuid holland: 38
tasmania: 38
kyoto: 38
aveiro: 38
unknown: 38
dorset: 37
thueringen: 37
toapayoh: 37
subang jaya: 37
neuchâtel: 36
keski-suomi: 36
ge: 36
lorraine: 35
ny: 35
sussex: 34
aquitaine: 34
aargau: 33
uppland: 33
alava: 33
bari: 33
cascais: 33
ncr: 32
umbria: 32
maraval: 32
quinta región: 32
kedah: 32
isle of wight: 31
mississippi39571: 30
armed forces pacific: 30
dtto federal: 30
friuli venezia giulia: 30
hong kong: 30
yedor: 29
provence alpes côte d`azur: 29
west midlands: 28
cataluña: 28
lombardy: 28
fukuoka: 28
varsinais-suomi: 28
dolj: 28
distrito federal: 27
zh: 27
zurich: 27
my own little world: 27
bulacan: 27
middlesex: 26
jalisco: 26
haute-saône: 25
virgin islands: 25
east yorkshire: 25
idf: 24
navarra: 24
s. carolina: 24
medan hawalli: 24
manchester: 24
spain: 24
sjælland: 23
.: 23
normandy: 23
va: 23
conwy: 23
my infinite mind: 22
ostfriesland: 22
vienne: 22
essex: 22
reykjavik: 22
miraflores: 22
toamasina: 22
vaslui: 22
wicklow: 21
abruzzo: 21
cumbria: 21
islas canarias: 21
côte d`azur: 21
granollers: 21
trás-os-montes: 21
ma: 20
ilfov: 20
baselland: 20
st.gallen: 20
castilla-la mancha: 20
vigo pontevedra: 20
oxford: 20
lincolnshire: 19
yvelines: 19
île de france: 19
vientiane: 19
brandenburg: 19
nunavut: 18
badajoz: 18
solothurn: 18
haineut: 17
zhejiang: 17
leiria: 17
schaffhausen: 17
el bierzo: 17
euskal herria: 17
haute-savoie: 17
basel: 17
catalunya - barcelona: 16
oxfordshire: 16
leicestershire: 16
galicia: 16
málaga: 16
oxon: 16
sichuan: 16
liege: 16
western pennsylvania: 16
armed services europe: 16
indre et loire: 16
país valencià: 16
aberdeenshire: 16
västra götalands län: 16
sardegna: 15
groningen: 15
estado de méxico: 15
sharon: 15
ile d`oleron: 15
thüringen: 15
maharashtra: 15
guernsey: 15
uk: 15
north lincolnshire: 14
saarland: 14
kyiv: 14
istanbul: 14
east java: 14
cebu: 14
seoul: 14
delhi: 13
bacau: 13
florida keys: 13
alto alentejo: 13
nord-pas-de-calais: 13

In [ ]:
# for i in range(len(df)):
#   df['state'][i] = df['state'][i].strip()
df['state']=df['state'].str.strip()

In [ ]:
df

,ID,User-ID,Book-ID,Book-Rating,Age,Location,Book-Title,Book-Author,Year-Of-Publication,Publisher,town,state,country
0,TRAIN_000012,USER_00003,BOOK_006281,9,24.0,"magdeburg, sachsen-anhalt, germany",Wir sind Erinnerung. GedÃ?Â¤chtnis und PersÃ?Â...,Daniel L. Schacter,2001.0,Rowohlt Tb.,magdeburg,sachsen-anhalt,germany
1,TRAIN_000013,USER_00003,BOOK_017583,7,24.0,"magdeburg, sachsen-anhalt, germany",2061. Odyssee III. Roman.,Arthur C. Clarke,2000.0,Heyne,magdeburg,sachsen-anhalt,germany
2,TRAIN_000014,USER_00003,BOOK_047847,7,24.0,"magdeburg, sachsen-anhalt, germany",Die Jury. Roman.,John Grisham,1992.0,Heyne,magdeburg,sachsen-anhalt,germany
3,TRAIN_000015,USER_00003,BOOK_058657,8,24.0,"magdeburg, sachsen-anhalt, germany",Frisch gepreÃ?Â?t.,Susanne FrÃ?Â¶hlich,2000.0,Ullstein Buchverlage GmbH &amp; Co. KG / Ullst...,magdeburg,sachsen-anhalt,germany
4,TRAIN_000016,USER_00003,BOOK_097106,6,24.0,"magdeburg, sachsen-anhalt, germany",Hitlers Helfer.,Guido Knopp,1998.0,Goldmann,magdeburg,sachsen-anhalt,germany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
697104,TRAIN_871381,USER_92093,BOOK_267033,10,37.0,"lakewood, colorado, usa","Tea Time/Tradition, Presentation, and Recipes ...",M. Dalton King,1992.0,Running Press Book Publishers,lakewood,colorado,usa
697105,TRAIN_871382,USER_92093,BOOK_267657,8,37.0,"lakewood, colorado, usa","Gates of Zion (Thoene, Bodie, Zion Chronicles,...",Bodie Thoene,1986.0,Bethany House,lakewood,colorado,usa
697106,TRAIN_871383,USER_92093,BOOK_267890,0,37.0,"lakewood, colorado, usa","Girlfriends: Invisible Bonds, Enduring Ties",Carmen Renee Berry,1995.0,Wildcat Canyon Press,lakewood,colorado,usa
697107,TRAIN_871384,USER_92093,BOOK_268377,8,37.0,"lakewood, colorado, usa","When Hope Springs New (Canadian West, Book 4)",Janette Oke,1986.0,Bethany House,lakewood,colorado,usa
697108,TRAIN_871385,USER_92093,BOOK_269242,7,37.0,"lakewood, colorado, usa",A Sand County Almanac and Sketches Here and Th...,Aldo Leopold,1989.0,Oxford University Press,lakewood,colorado,usa

In [ ]:
def extract_top_attributes(column):
    counter = Counter(column)
    total_count = sum(counter.values())
    sorted_counts = sorted(counter.items(), key=lambda x: x[1], reverse=True)

    cumulative_percentage = 0
    extracted_attributes = []

    for value, count in sorted_counts:
        cumulative_percentage += count / total_count
        extracted_attributes.append(value)

        if cumulative_percentage >= 0.6:

            break

    return extracted_attributes

In [ ]:
top_attributes = extract_top_attributes(df['state'])
print(top_attributes)
# 60% 기준으로 잘라서 범주화하고 나머지는 'others'로 분류

['california', 'texas', 'ontario', 'missouri', 'florida', 'washington', 'illinois', 'georgia', 'virginia', 'minnesota', 'new york', 'pennsylvania', 'north carolina', 'n/a', 'ohio', 'england', 'new jersey', '', 'oregon', 'michigan']

In [ ]:
test=[]
for j in range(len(top_attributes)):
  if len(top_attributes[j]) >= 4:
    test.append(top_attributes[j])

In [ ]:
test

['california',
 'texas',
 'ontario',
 'missouri',
 'florida',
 'washington',
 'illinois',
 'georgia',
 'virginia',
 'minnesota',
 'new york',
 'pennsylvania',
 'north carolina',
 'ohio',
 'england',
 'new jersey',
 'oregon',
 'michigan']

In [ ]:
for i in range(len(df)):
  if df['state'][i] not in test:
    df['state'][i] = 'others'

<ipython-input-10-0478a1909c0f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['state'][i] = 'others'

In [ ]:
def delete_column(dataframe, column_name):
    dataframe.drop(column_name, axis=1, inplace=True)

In [ ]:
delete_column(df, ['Location','town','country'])

In [ ]:
delete_column(df, ['ID','Book-ID'])

In [ ]:
for i in range(len(df)):
  if df['state'][i] == ' texas':
    df['state'][i] = 'texas'
  elif df['state'][i] == ' california':
    df['state'][i] = 'california'

In [ ]:
Counter(df['state'])

Counter({'others': 299656,
         'ohio': 13627,
         'michigan': 12410,
         'texas': 30246,
         'illinois': 21057,
         'virginia': 20046,
         'california': 74617,
         'ontario': 27956,
         'pennsylvania': 16124,
         'england': 13276,
         'minnesota': 18999,
         'new york': 18346,
         'oregon': 12523,
         'washington': 21365,
         'georgia': 20286,
         'missouri': 24918,
         'florida': 23000,
         'new jersey': 13067,
         'north carolina': 15590})

In [ ]:
for i in range(len(df)):
  if df['state'][i] == 'califonia':
    df['state'][i] = 'california'

<ipython-input-53-b0b83c095ace>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['state'][i] = 'california'

In [ ]:
Counter(df['state'])

Counter({'others': 294975,
         'michigan': 10794,
         'ontario': 22457,
         'north carolina': 12522,
         'illinois': 16177,
         'england': 9412,
         'washington': 16588,
         'oregon': 10285,
         'ohio': 11336,
         'wisconsin': 6203,
         'california': 73409,
         'texas': 29892,
         'virginia': 15522,
         'georgia': 17745,
         'new york': 14424,
         'tennessee': 7635,
         'british columbia': 7212,
         'florida': 16171,
         'minnesota': 17774,
         'massachusetts': 5839,
         'maryland': 9187,
         'nebraska': 6301,
         'alberta': 6369,
         'new jersey': 11098,
         'pennsylvania': 11352,
         'missouri': 19783,
         'arizona': 7962})

In [ ]:
df['state'] = df['state'].astype('category') # 범주형으로 변환

# 나이 범주화

In [ ]:
df['Age'].describe()

count    697109.000000
mean         37.063245
std          12.154988
min           0.000000
25%          31.000000
50%          35.000000
75%          42.000000
max         239.000000
Name: Age, dtype: float64

In [ ]:
Counter(df['Age'])

Counter({24.0: 12328,
         37.0: 15418,
         49.0: 10073,
         39.0: 12580,
         40.0: 10152,
         43.0: 15682,
         29.0: 21918,
         23.0: 12775,
         31.0: 19290,
         83.0: 144,
         26.0: 15122,
         30.0: 19699,
         53.0: 4308,
         46.0: 13404,
         33.0: 24082,
         35.0: 181862,
         34.0: 18548,
         103.0: 354,
         28.0: 18697,
         18.0: 5310,
         27.0: 15605,
         42.0: 7317,
         20.0: 3539,
         4.0: 237,
         55.0: 3257,
         25.0: 15290,
         50.0: 6390,
         38.0: 16179,
         32.0: 18881,
         45.0: 8883,
         36.0: 18949,
         51.0: 10540,
         21.0: 6704,
         62.0: 7446,
         60.0: 2107,
         52.0: 12314,
         54.0: 6542,
         10.0: 93,
         59.0: 1517,
         41.0: 11520,
         17.0: 2839,
         48.0: 4920,
         65.0: 2227,
         3.0: 89,
         63.0: 2098,
         47.0: 13366,
         57.0: 6057,
         22.0: 7567,
         56.0: 6109,
         44.0: 17213,
         14.0: 1579,
         58.0: 7365,
         71.0: 487,
         67.0: 2279,
         16.0: 1452,
         61.0: 3116,
         19.0: 2378,
         68.0: 284,
         66.0: 494,
         75.0: 98,
         101.0: 92,
         11.0: 353,
         12.0: 462,
         168.0: 40,
         77.0: 79,
         70.0: 169,
         8.0: 409,
         15.0: 1685,
         209.0: 16,
         1.0: 231,
         136.0: 97,
         0.0: 242,
         69.0: 658,
         74.0: 66,
         13.0: 597,
         64.0: 474,
         2.0: 157,
         76.0: 74,
         239.0: 116,
         5.0: 71,
         228.0: 48,
         100.0: 101,
         72.0: 265,
         204.0: 93,
         82.0: 55,
         73.0: 56,
         97.0: 127,
         81.0: 145,
         104.0: 95,
         80.0: 99,
         220.0: 15,
         79.0: 57,
         7.0: 66,
         9.0: 1263,
         78.0: 58,
         116.0: 960,
         92.0: 24,
         90.0: 43,
         84.0: 17,
         148.0: 47,
         201.0: 285,
         93.0: 14,
         151.0: 15})

In [ ]:
df = df[df['Age']<=120] # 이상치 제거

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
for i in range(len(df)):
  if df['Age'][i] < 10.0:
    df['Age'][i] = '0-9'
  elif 10.0 <= df['Age'][i] < 15.0:
    df['Age'][i] = '10-14'
  elif 15.0 <= df['Age'][i] < 20.0:
    df['Age'][i] = '15-19'
  elif 20.0 <= df['Age'][i] < 25.0:
    df['Age'][i] = '20-24'
  elif 25.0 <= df['Age'][i] < 30.0:
    df['Age'][i] = '25-29'
  elif 30.0 <= df['Age'][i] < 35.0:
    df['Age'][i] = '30-34'
  elif 35.0 <= df['Age'][i] < 40.0:
    df['Age'][i] = '35-39'
  elif 40.0 <= df['Age'][i] < 45.0:
    df['Age'][i] = '40-44'
  elif 45.0 <= df['Age'][i] < 50.0:
    df['Age'][i] = '45-49'
  elif 50.0 <= df['Age'][i] < 55.0:
    df['Age'][i] = '50-54'
  elif 55.0 <= df['Age'][i] < 60.0:
    df['Age'][i] = '55-59'
  elif 60.0 <= df['Age'][i] < 65.0:
    df['Age'][i] = '60-64'
  elif 65.0 <= df['Age'][i] < 70.0:
    df['Age'][i] = '65-69'
  elif 70.0 <= df['Age'][i] < 75.0:
    df['Age'][i] = '70-74'
  elif 75.0 <= df['Age'][i] < 80.0:
    df['Age'][i] = '75-79'
  elif 80.0 <= df['Age'][i] < 85.0:
    df['Age'][i] = '80-84'
  elif 85.0 <= df['Age'][i] < 90.0:
    df['Age'][i] = '85-89'
  else:
    df['Age'][i] = '90+'

<ipython-input-22-c1e1e85487bf>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'][i] = '20-24'

In [ ]:
df['Age'] = df['Age'].astype('category')

In [ ]:
df

,User-ID,Book-Rating,Age,Book-Title,Book-Author,Year-Of-Publication,Publisher,state
0,USER_00003,9,20-24,Wir sind Erinnerung. GedÃ?Â¤chtnis und PersÃ?Â...,Daniel L. Schacter,2001.0,Rowohlt Tb.,others
1,USER_00003,7,20-24,2061. Odyssee III. Roman.,Arthur C. Clarke,2000.0,Heyne,others
2,USER_00003,7,20-24,Die Jury. Roman.,John Grisham,1992.0,Heyne,others
3,USER_00003,8,20-24,Frisch gepreÃ?Â?t.,Susanne FrÃ?Â¶hlich,2000.0,Ullstein Buchverlage GmbH &amp; Co. KG / Ullst...,others
4,USER_00003,6,20-24,Hitlers Helfer.,Guido Knopp,1998.0,Goldmann,others
...,...,...,...,...,...,...,...,...
696332,USER_92093,10,35-39,"Tea Time/Tradition, Presentation, and Recipes ...",M. Dalton King,1992.0,Running Press Book Publishers,others
696333,USER_92093,8,35-39,"Gates of Zion (Thoene, Bodie, Zion Chronicles,...",Bodie Thoene,1986.0,Bethany House,others
696334,USER_92093,0,35-39,"Girlfriends: Invisible Bonds, Enduring Ties",Carmen Renee Berry,1995.0,Wildcat Canyon Press,others
696335,USER_92093,8,35-39,"When Hope Springs New (Canadian West, Book 4)",Janette Oke,1986.0,Bethany House,others
696336,USER_92093,7,35-39,A Sand County Almanac and Sketches Here and Th...,Aldo Leopold,1989.0,Oxford University Press,others

# 출판연도 처리

In [ ]:
df['Year-Of-Publication'].describe()

count    696337.000000
mean       1972.359348
std         211.697156
min          -1.000000
25%        1991.000000
50%        1997.000000
75%        2001.000000
max        2021.000000
Name: Year-Of-Publication, dtype: float64

In [ ]:
Counter(df['Year-Of-Publication'])

Counter({2001.0: 51206,
         2000.0: 47264,
         1992.0: 25020,
         1998.0: 42376,
         1999.0: 49879,
         1996.0: 39988,
         1993.0: 26920,
         1997.0: 39558,
         2003.0: 48094,
         2002.0: 57866,
         1995.0: 36945,
         2004.0: 17301,
         1994.0: 31599,
         1991.0: 23204,
         1989.0: 18023,
         1976.0: 2764,
         -1.0: 7913,
         1983.0: 8948,
         1990.0: 21524,
         1986.0: 12081,
         1987.0: 13814,
         1979.0: 3214,
         1971.0: 805,
         1985.0: 10060,
         1988.0: 14942,
         1982.0: 7560,
         1980.0: 4124,
         1978.0: 3474,
         1984.0: 9889,
         1981.0: 5430,
         1959.0: 369,
         1953.0: 373,
         1974.0: 1496,
         1969.0: 606,
         1966.0: 289,
         1965.0: 421,
         1970.0: 924,
         1977.0: 2853,
         1975.0: 1447,
         1968.0: 376,
         1973.0: 1247,
         2021.0: 40,
         1967.0: 245,
         1943.0: 15,
         1952.0: 58,
         1972.0: 1130,
         1930.0: 55,
         1964.0: 250,
         1956.0: 110,
         1961.0: 234,
         1960.0: 266,
         1958.0: 142,
         1941.0: 15,
         1955.0: 150,
         1963.0: 235,
         1947.0: 19,
         1957.0: 183,
         1923.0: 37,
         1962.0: 207,
         1954.0: 154,
         2005.0: 92,
         1927.0: 11,
         1942.0: 39,
         1949.0: 17,
         1950.0: 44,
         1920.0: 67,
         1948.0: 20,
         1940.0: 42,
         1901.0: 5,
         1929.0: 11,
         1951.0: 56,
         2020.0: 7,
         1911.0: 21,
         1931.0: 3,
         1945.0: 21,
         1946.0: 36,
         1937.0: 14,
         1938.0: 8,
         1932.0: 14,
         1928.0: 2,
         1939.0: 8,
         1925.0: 3,
         1936.0: 10,
         2006.0: 2,
         1944.0: 3,
         1378.0: 1,
         1900.0: 1,
         2011.0: 6,
         1902.0: 10,
         1926.0: 8,
         1904.0: 1,
         1924.0: 3,
         1921.0: 2,
         2010.0: 1,
         1914.0: 1,
         2008.0: 1,
         1806.0: 1,
         1906.0: 1,
         1933.0: 4,
         1935.0: 3,
         1934.0: 1,
         1922.0: 2,
         1897.0: 1,
         2012.0: 1,
         1917.0: 1})

In [ ]:
df=df[df['Year-Of-Publication'] != -1.0] # 7913개의 Outlier 제거

In [ ]:
column_name = 'Year-Of-Publication'
has_null = df[column_name].isnull().any()

if has_null:
    # 결측치가 있는 행 제거
    df = df.dropna(subset=[column_name])

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
for i in range(len(df)):
  if df['Year-Of-Publication'][i] < 1980.0:
    df['Year-Of-Publication'][i] = '-1980'
  elif 1980.0 <= df['Year-Of-Publication'][i] < 1985.0:
    df['Year-Of-Publication'][i] = '1980-1984'
  elif 1985.0 <= df['Year-Of-Publication'][i] < 1990.0:
    df['Year-Of-Publication'][i] = '1985-1989'
  elif 1990.0 <= df['Year-Of-Publication'][i] < 1995.0:
    df['Year-Of-Publication'][i] = '1990-1994'
  elif 1995.0 <= df['Year-Of-Publication'][i] < 2000.0:
    df['Year-Of-Publication'][i] = '1995-1999'
  else:
    df['Year-Of-Publication'][i] = '2000+'

<ipython-input-30-cb0172f9dff8>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year-Of-Publication'][i] = '2000+'

In [ ]:
df['Year-Of-Publication'] = df['Year-Of-Publication'].astype('category')

# 확인

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 688424 entries, 0 to 688423
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   User-ID              688424 non-null  object
 1   Book-Rating          688424 non-null  int64
 2   Age                  688424 non-null  category
 3   Book-Title           688424 non-null  object
 4   Book-Author          688424 non-null  object
 5   Year-Of-Publication  688424 non-null  category
 6   Publisher            688424 non-null  object
 7   state                688424 non-null  category
dtypes: category(3), int64(1), object(4)
memory usage: 28.2+ MB

In [ ]:
df

,User-ID,Book-Rating,Age,Book-Title,Book-Author,Year-Of-Publication,Publisher,state
0,USER_00003,9,20-24,Wir sind Erinnerung. GedÃ?Â¤chtnis und PersÃ?Â...,Daniel L. Schacter,2000+,Rowohlt Tb.,others
1,USER_00003,7,20-24,2061. Odyssee III. Roman.,Arthur C. Clarke,2000+,Heyne,others
2,USER_00003,7,20-24,Die Jury. Roman.,John Grisham,1990-1994,Heyne,others
3,USER_00003,8,20-24,Frisch gepreÃ?Â?t.,Susanne FrÃ?Â¶hlich,2000+,Ullstein Buchverlage GmbH &amp; Co. KG / Ullst...,others
4,USER_00003,6,20-24,Hitlers Helfer.,Guido Knopp,1995-1999,Goldmann,others
...,...,...,...,...,...,...,...,...
688419,USER_92093,10,35-39,"Tea Time/Tradition, Presentation, and Recipes ...",M. Dalton King,1990-1994,Running Press Book Publishers,others
688420,USER_92093,8,35-39,"Gates of Zion (Thoene, Bodie, Zion Chronicles,...",Bodie Thoene,1985-1989,Bethany House,others
688421,USER_92093,0,35-39,"Girlfriends: Invisible Bonds, Enduring Ties",Carmen Renee Berry,1995-1999,Wildcat Canyon Press,others
688422,USER_92093,8,35-39,"When Hope Springs New (Canadian West, Book 4)",Janette Oke,1985-1989,Bethany House,others
688423,USER_92093,7,35-39,A Sand County Almanac and Sketches Here and Th...,Aldo Leopold,1985-1989,Oxford University Press,others

In [ ]:
df.to_csv('final.csv')

In [ ]:
df_test_3 = pd.read_csv('test_2.csv',encoding = 'utf-8-sig', index_col = 0)
df_train_3= pd.read_csv('train_2.csv',encoding = 'utf-8-sig',  index_col = 0)
df_submission = pd.read_csv('sample_submission.csv',encoding = 'utf-8-sig')

user_idx = df_train_3['User-ID'].value_counts()[df_train_3['User-ID'].value_counts().cumsum() <= df_train_3['User-ID'].value_counts().sum()* 0.8].index
book_idx = df_train_3['Book-ID'].value_counts()[df_train_3['Book-ID'].value_counts().cumsum() <= df_train_3['Book-ID'].value_counts().sum()* 0.8].index
user_indices = [True  if i in user_idx else False for i in df_train_3['User-ID']]
book_indices = [True  if i in book_idx else False for i in df_train_3['Book-ID']]
pd.DataFrame(np.array(user_indices) * np.array(book_indices)).value_counts()